name: py37_pikapi
channels:
  - conda-forge
  - defaults
dependencies:
  - pip:
    - numpy==1.18.2
    - opencv-python==4.2.0.34
    - pandas==1.0.3
    - plotly==4.6.0
    - pyqt5-sip==4.19.18
    - scikit-image==0.16.2
    - scikit-learn==0.22.2.post1
    - scipy==1.4.1
    - shapely==1.7.0
    - sklearn==0.0
    - streamlit==0.61.0